"""add artifacts to messages

Revision ID: 7e9f2871c08b
Revises: 63d4910589ea
Create Date: 2026-07-31 15:09:51.865692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e9f2871c08b"
down_revision: Union[str, Sequence[str], None] = "63d4910589ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checkpoint_migrations")
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index(
        op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes"
    )
    op.drop_table("checkpoint_writes")
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.add_column(
        "messages",
        sa.Column(
            "artifacts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("messages", "artifacts")
